services:
  memorial-app:
    image: memorial-app:latest
    container_name: memorial-app
    restart: always
    ports:
      - "7554:7554"
    volumes:
      - ./data:/app/data
      - ./photos:/app/photos
