services:
  memorial-app:
    image: memorial-app:latest
    container_name: memorial-app
    restart: always
    ports:
      - "80:7554"
    volumes:
      - ./data:/app/backend/data
      - ./photos:/app/backend/photos
